### ISSUE TITLE
Install mysql locally

### ISSUE THREAD

**Issue by thewoolleyman** [jahjahjah/R000by#2]
If you have a mac, installing via homebrew is recommended.  Google "brew install mysql" and you'll get various hits - skim them pick one that seems up-to-date and relevant to your version of OSX.

Protip - do the search in a new Chrome window, then CMD-click the results that look interesting so they open in new tabs in the background.  Benefits:
- pre-loaded for easy perusal
- don't get mixed up with your other unrelated tabs
- easy to close the whole window and all tabs when you're done with the search/task.

**Comment by jahjahjah** [comment]
Installed. Will load files now.
